source 'https://github.com/CocoaPods/Specs.git'


workspace 'TraditionMVC.xcworkspace'
xcodeproj 'TraditionMVC/TraditionMVC.xcworkspace'

target ‘TraditionMVC’ do
  platform :ios, ‘9.0’
  xcodeproj 'TraditionMVC/TraditionMVC.xcworkspace'
  pod 'AFNetworking',  '~> 3.0’
  pod 'MJRefresh’
  pod 'ReactiveCocoa','~>2.1.8'
  pod 'Masonry'
end

