source 'https://github.com/CocoaPods/Specs.git'


workspace 'VIPER.xcworkspace'
xcodeproj 'VIPER/VIPER.xcworkspace'

target ‘VIPER’ do
  platform :ios, ‘9.0’
  xcodeproj 'VIPER/VIPER.xcworkspace'
  pod 'AFNetworking',  '~> 3.0’
  pod 'MJRefresh’
  pod 'ReactiveCocoa','~>2.1.8'
  pod 'Masonry'
end

