source 'https://github.com/CocoaPods/Specs.git'


workspace 'MVP.xcworkspace'
xcodeproj 'MVP/MVP.xcworkspace'

target ‘MVP’ do
  platform :ios, ‘9.0’
  xcodeproj 'MVP/MVP.xcworkspace'
  pod 'AFNetworking',  '~> 3.0’
  pod 'MJRefresh’
  pod 'ReactiveCocoa','~>2.1.8'
  pod 'Masonry'
end

