source 'https://github.com/CocoaPods/Specs.git'


workspace 'AppleMVC.xcworkspace'
xcodeproj 'AppleMVC/AppleMVC.xcworkspace'

target ‘AppleMVC’ do
  platform :ios, ‘9.0’
  xcodeproj 'AppleMVC/AppleMVC.xcworkspace'
  pod 'AFNetworking',  '~> 3.0’
  pod 'MJRefresh’
  pod 'ReactiveCocoa','~>2.1.8'
  pod 'Masonry'
end

