source 'https://github.com/CocoaPods/Specs.git'


workspace 'MVVM.xcworkspace'
xcodeproj 'MVVM/MVVM.xcworkspace'

target ‘MVVM’ do
  platform :ios, ‘9.0’
  xcodeproj 'MVVM/MVVM.xcworkspace'
  pod 'AFNetworking',  '~> 3.0’
  pod 'MJRefresh’
  pod 'ReactiveCocoa','~>2.1.8'
  pod 'Masonry'
end

